name: build
on: [push, pull_request, workflow_dispatch]
jobs:
  linux_build:
    name: 'Linux Build'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Build applications
        run: |
          cmake --version
          cmake -S . -B build
          cmake --build build

  windows_build:
    name: 'Windows Build'
    runs-on: 'windows-latest'
    steps:
      - uses: actions/checkout@v1
      - name: Install msys
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run: |
          $msyspath="msys64"
          choco install msys2 --params="/InstallDir:$msyspath /NoPath" -y
          echo "::add-path::$msyspath\usr\bin"
          echo "::add-path::$msyspath"
          echo "::add-path::$msyspath\mingw64\bin"
          echo "::add-path::$msyspath\mingw64\lib"
          echo "::add-path::$msyspath\mingw64\include"
      - name: Install compiler
        run: |
          pacman --noconfirm -Syu
          pacman --noconfirm -S mingw-w64-x86_64-gcc
      - name: Build applications
        run: |
          cmake --version
          cmake -S . -B build -G "MSYS Makefiles"
          cmake --build build
