name: cpplint
on: [push, pull_request, workflow_dispatch]
jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: pip install cpplint
    - run: cpplint --recursive .
    - run: |
        NOLINT=$(grep -rs NOLINT ./* | wc -l | awk '{print $1}')
        if [[ $NOLINT -ne 0 ]]
        then
            echo "Use of NOLINT is forbidden! Don't be lazy and fix style errors."
            exit 1
        fi
    - run: if [[ ! -s client/client.cpp ]]; then echo 'No client code found'; exit 1; fi
    - run: if [[ ! -s server/server.cpp ]]; then echo 'No server code found'; exit 1; fi
