name: tests

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Build applications'
        run: |
          cmake --version
          cmake -S . -B build
          cmake --build build
      - run: build/bin/tests_server
      - run: build/bin/tests_server "Kitel Boris"
      - run: build/bin/tests_server 3425

  test_connection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        run: |
          cmake --version
          cmake -S . -B build
          cmake --build build
      - run: |
          build/bin/server 50000 &
          sleep 5
          build/bin/tests_client_plug 50000